### ISSUE TITLE
About the environment?

### ISSUE THREAD

**Issue by xiaofeng-c** [LiewFeng/imTED#11]
Thank you for your work,i would llike to know the environment of your project, such as the version of mmcv, it seems can't work with high version.

**Comment by LiewFeng** [comment]
Hi, you may refer to [this](https://github.com/LiewFeng/imTED/blob/main/docs/get_started.md). Our code is based on mmdet 2.11.0.

**Comment by xiaofeng-c** [comment]
Ok,i get it, many thanks.

**Comment by HappyGoLucky6666** [comment]
Have you successfully replicated the project's results from this paper? I also encountered issues while setting up the environment. Could you please share your environment configuration with me? I would appreciate it if you could include detailed version information for all the libraries so that I can run the experiment successfully on my local machine. Thank you.@xiaofeng-c
