### ISSUE TITLE
COCO JSON file formatting for finetuning

### ISSUE THREAD

**Issue by amajee11us** [LiewFeng/imTED#22]
Hi, The config file for finetuning accepts only 1 json for train but in the data preparation steps show that there are multiple json files (http://dl.yf.io/fs-det/datasets/cocosplit/) for each class.
Can you please let me know the steps how you combined these files ?

**Comment by LiewFeng** [comment]
Hi, @amajee11us , sorry for the late reply. The downloading link of json files is updated in the README. You can download [it](https://mailsucasaccn-my.sharepoint.com/:u:/g/personal/liufeng20_mails_ucas_ac_cn/EdDDuaUiWvlImzOHddcsGfkBHp0Me1zFMm20zGHz9l8alg?e=U3gx2I) directly.

**Comment by HappyGoLucky6666** [comment]
Have you successfully replicated the project's results from this paper? I encountered issues while setting up the environment. Could you please share your environment configuration with me? I would appreciate it if you could include detailed version information for all the libraries so that I can run the experiment successfully on my local machine. Thank you.@amajee11us
